### ISSUE TITLE
Fetch Covid-19 data

### ISSUE THREAD

**Issue by yelloweq** [yelloweq/bootcamp-covid-app#3]
What kind of data do we need to fetch along side the number of covid cases? Place information? How often do we update it?

**Comment by IBN5101** [comment]
1) COVID case should be divided into: current case / recovered / deaths
2) The information for now should be in the scope of UK, maybe starting with the major cities (Birmingham, London)
3) We update it every week + manually. Once we have a solid app, we can increase the frequency to every 3 days / every day.

**Comment by yelloweq** [comment]
Possible data sources:
https://covid19.mathdro.id/api (needs verification)
https://github.com/CSSEGISandData/COVID-19 (US only)
https://coronavirus.data.gov.uk/

**Comment by snim2** [comment]
This might be useful: https://coronavirus.data.gov.uk/details/developers-guide
