### ISSUE TITLE
Create page routing with react router

### ISSUE THREAD

**Issue by yelloweq** [yelloweq/bootcamp-covid-app#9]
Dynamically load pages as elements in App.js

**Comment by yelloweq** [comment]
Good tutorial: https://www.youtube.com/watch?v=Law7wfdg_ls

**Comment by yelloweq** [comment]
App.js should by default route '/ ' to the landing page named 'Home' in './components/pages/Home'
Then new pages should include new components, for instance, the graph page should have the graph component and navigation.

**Comment by Daniel-Singer** [comment]
Hi! 
Is someone working on this issue already? Would like to give it a go :)

**Comment by yelloweq** [comment]
Hi, sorry but this project is something we are doing as a group for a bootcamp and cannot really accept outside help 😅

**Comment by Daniel-Singer** [comment]
Oh, sorry! Have fun with the project
